name: Deploy to GitHub Pages

on:
  push:
    branches:
      # - main
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare for deployment
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            mkdir -p deploy
            cp -r src/* deploy/
          elif [ "${GITHUB_REF##*/}" = "dev" ]; then
            mkdir -p deploy/dev
            cp -r src/* deploy/dev/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
