name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set publish branch and directory
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            export PUBLISH_BRANCH="main"
            export PUBLISH_DIR="src"
          elif [ "${GITHUB_REF##*/}" = "dev" ]; then
            export PUBLISH_BRANCH="gh-pages"
            export PUBLISH_DIR="src/dev"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $PUBLISH_DIR
          publish_branch: $PUBLISH_BRANCH
